version: "3"

services:
  nginx:
    build:
      dockerfile: Dockerfile.dev
      # context: ./nginx
      context: ./nginx-letsencrypt
    restart: always
    ports:
      - "3050:80"
    links:
      - client:client
      - api:api
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    restart: always
    volumes:
      - /app/node_modules
      - ./client:/app
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    restart: always
    volumes:
      - /app/node_modules
      - ./server:/app
